apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  version: major
  version_number: "2.0"
  componente_grel: caapi-apro-base-originacao-proposta-v2
  tipo_autenticacao: oauth-2.0
  criticidade: extrema
  exposure:
    - interna
    - externa
  issue_demanda: CAASP-18057
  name: petstore-api
  description: The petstore API
  tags:
    - store
    - rest
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
    - url: https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: experimental
  owner: squad-roma
  definition:
    $text: ./petstore.oas.yaml
